# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 12:08
from __future__ import unicode_literals

from django.db import migrations
import organizations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_model_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=organizations.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from=b'name', unique=True),
        ),
    ]
